# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: greeter/v1/service.proto for package 'Greeter.V1'

require 'grpc'
require 'greeter/v1/service_pb'

module Greeter
  module V1
    module Service
      # Greeter sends greetings.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'greeter.v1.Service'

        # Hello to name.
        rpc :Hello, ::Greeter::V1::HelloRequest, ::Greeter::V1::HelloResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
