# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter/v1/service.proto

require 'google/protobuf'


descriptor_data = "\n\x18greeter/v1/service.proto\x12\ngreeter.v1\"\"\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\")\n\rHelloResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2G\n\x07Service\x12<\n\x05Hello\x12\x18.greeter.v1.HelloRequest\x1a\x19.greeter.v1.HelloResponseBCZ3github.com/alexfalkowski/go-monolith/api/greeter/v1\xea\x02\x0bGreeter::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Greeter
  module V1
    HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.v1.HelloRequest").msgclass
    HelloResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.v1.HelloResponse").msgclass
  end
end
