# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echoer/v1/service.proto

require 'google/protobuf'


descriptor_data = "\n\x17\x65\x63hoer/v1/service.proto\x12\techoer.v1\"\'\n\x0b\x45\x63hoRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\"(\n\x0c\x45\x63hoResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2B\n\x07Service\x12\x37\n\x04\x45\x63ho\x12\x16.echoer.v1.EchoRequest\x1a\x17.echoer.v1.EchoResponseBAZ2github.com/alexfalkowski/go-monolith/api/echoer/v1\xea\x02\nEchoer::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Echoer
  module V1
    EchoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("echoer.v1.EchoRequest").msgclass
    EchoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("echoer.v1.EchoResponse").msgclass
  end
end
