# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: echoer/v1/service.proto for package 'Echoer.V1'

require 'grpc'
require 'echoer/v1/service_pb'

module Echoer
  module V1
    module Service
      # Service allows to echoes to be sent.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'echoer.v1.Service'

        # Echo the request in the response.
        rpc :Echo, ::Echoer::V1::EchoRequest, ::Echoer::V1::EchoResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
